# HTTP server settings
port = 8080
allow_origin = ["*"]
jwt_key = "foobar"
static_dir = "static"

# Database settings
sqlite_path = "core.db"

# Other settings
max_query_day = 5
lock_advanced_minute = 5
lock_port = "8888"
lock_cmd = "AAAAAAAA"